services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ms-productos
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/db:/var/lib/postgres/data # Asegurarse que docker-data/db existe
    networks:
      - dbnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: juankaprin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8032:80
    depends_on:
      - db
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge
